### ISSUE TITLE
Dash inputs get dropped sometimes.

### ISSUE THREAD

**Issue by tiboedturtels** [momo1478/Kickshot#5]
Its because it consumes inputs in a collision function, which is runs on same frame cycles as FixedUpdate, while input is based on the global Update loop.  From here on make sure you call methods like GetButtonDown and GetButtonUp from the Update method.

**Comment by momo1478** [comment]
Ah, my bad. Wasn't even thinking to put physics related things in Fixed Update when they should always be there.
